baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nick Gohman | TIL'
theme = 'xmin'


[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 3

